2024-01-11T21:58:20.492525+0600 INFO Check
2024-01-11T21:59:34.824740+0600 INFO Check
2024-01-11T21:59:34.825003+0600 INFO ("[1] to calibrate
" "[2] to start measure
>")
2024-01-11T21:59:43.761850+0600 INFO Start calibrate function
2024-01-11T21:59:43.762517+0600 ERROR calibrate Fail: create_config() takes 0 positional arguments but 1 was given
2024-01-11T21:59:43.763067+0600 ERROR Calibrate or start Error: local variable 'arduino' referenced before assignment
2024-01-11T22:26:01.403172+0600 INFO Check
2024-01-11T22:26:01.403466+0600 INFO 
Select an option:
[1] Calibrate
[2] Start Measurement
2024-01-11T22:26:09.830272+0600 DEBUG '[1;35mFeeder project.[0m'
2024-01-11T22:26:09.830997+0600 ERROR Error connecting: [Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
2024-01-11T22:26:09.831407+0600 ERROR start_weight Error: 'NoneType' object has no attribute '_get_measure'
2024-01-11T22:26:09.831740+0600 INFO Start weight: None
2024-01-11T22:26:09.832117+0600 INFO Start time: 2872.896311738
2024-01-11T22:26:09.832417+0600 INFO Start connect RFID function
2024-01-11T22:26:09.832706+0600 INFO  In the begin: Animal ID: b'435400040001'
2024-01-11T22:26:12.904116+0600 ERROR Error connect RFID reader [Errno 113] No route to host
2024-01-11T22:26:12.904867+0600 INFO Animal_id: None
2024-01-11T22:26:12.905272+0600 INFO Here is start while cycle
2024-01-11T22:26:12.905605+0600 ERROR Error: 'NoneType' object has no attribute '_get_measure'
2024-01-11T22:26:12.905989+0600 ERROR An error has been caught in function '<module>', process 'MainProcess' (10095), thread 'MainThread' (140341808947200):
Traceback (most recent call last):

  File "/home/maxat/Projects/Agrarka/feeder-installer/src/feeder_module.py", line 282, in feeder_module
    end_weight = weight._get_measure()
                 â”” None

AttributeError: 'NoneType' object has no attribute '_get_measure'


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

> File "/home/maxat/Projects/Agrarka/feeder-installer/src/main_feeder.py", line 32, in <module>
    main()
    â”” <function main at 0x7fa3ddec2d40>

  File "/home/maxat/Projects/Agrarka/feeder-installer/src/main_feeder.py", line 30, in main
    fdr.feeder_module()
    â”‚   â”” <function feeder_module at 0x7fa3ddec2c20>
    â”” <module 'feeder_module' from '/home/maxat/Projects/Agrarka/feeder-installer/src/feeder_module.py'>

  File "/home/maxat/Projects/Agrarka/feeder-installer/src/feeder_module.py", line 303, in feeder_module
    weight.disconnect()
    â”” None

AttributeError: 'NoneType' object has no attribute 'disconnect'
